name: IIIT Notebook
permalink: /:title:output_ext
collections:
    courses:
      output: true

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  - scope:
      path: ""
    values:
      layout: "default"
